apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: aws-idp-baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idp-app
  template:
    metadata:
      labels:
        app: idp-app
    spec:
      containers:
        - name: idp-app
          image: 065875800629.dkr.ecr.eu-central-1.amazonaws.com/idp-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000   # anpassen, falls deine App einen anderen Port nutzt
          env:
            # Beispiel: falls du ENV Variablen brauchst
            - name: NODE_ENV
              value: "production"