apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: aws-idp-baseline
spec:
  type: LoadBalancer
  selector:
    app: idp-app
  ports:
    - port: 80          # Port, über den von außen zugegriffen wird
      targetPort: 4000  # Port im Container (anpassen, falls anders)