apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bachelor-app
  template:
    metadata:
      labels:
        app: bachelor-app
    spec:
      containers:
        - name: bachelor-app
          image: europe-west1-docker.pkg.dev/project-3892995f-7fbd-4786-82f/azure-container-repo/idp-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
