apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: idp
spec:
  serviceName: "cockroachdb"
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:v23.2.2
          command:
            - "/bin/bash"
            - "-ecx"
            - |
              exec cockroach start-single-node --insecure --store=/cockroach/cockroach-data --http-port=8080 --listen-addr=0.0.0.0 --advertise-addr=cockroachdb
          ports:
            - containerPort: 26257 # SQL
            - containerPort: 8080  # Admin UI
          volumeMounts:
            - name: cockroach-data
              mountPath: /cockroach/cockroach-data
      volumes:
        - name: cockroach-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: idp
spec:
  clusterIP: None
  selector:
    app: cockroachdb
  ports:
    - port: 26257
      name: sql
    - port: 8080
      name: http
