apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-backend
  namespace: idp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
        - name: idp
          image: 065875800629.dkr.ecr.eu-central-1.amazonaws.com/idp-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000   # anpassen, falls deine App einen anderen Port nutzt
          env:
            # Beispiel: falls du ENV Variablen brauchst
            - name: NODE_ENV
              value: "production"