apiVersion: v1
kind: Service
metadata:
  name: idp-service
  namespace: idp
spec:
  type: ClusterIP
  selector:
    app: idp
  ports:
    - port: 80          # Port, über den von außen zugegriffen wird
      targetPort: 4000  # Port im Container (anpassen, falls anders)