name: Backend Build & Deploy to ECR

on:
  push:
    branches:
      - master      # oder main, falls dein Branch so hei√üt
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build backend Docker image
        working-directory: ./0.0.1/backend
        run: docker build -t backend .

      - name: Tag and push image to ECR
        env:
          AWS_ECR_URL: ${{ secrets.AWS_ECR_URL}}
        run: |
          echo "Using ECR URL: $AWS_ECR_URL"
          docker tag backend:latest $AWS_ECR_URL:latest
          docker push $AWS_ECR_URL:latest

      - name: Configure AWS credentials (ludwig-cli for EKS)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LUDWIG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LUDWIG }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Configure kubeconfig for EKS
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EKS_CLUSTER_NAME: bachelor-eks
          K8S_NAMESPACE: app-baseline
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy manifests to EKS
        run: |
          kubectl apply -f infra/K8s/namespace.yaml
          kubectl apply -f infra/K8s/deployment.yaml
          kubectl apply -f infra/K8s/service.yaml